# BEGIN 0000H

START:	   MVI D,0A	// OUTER LOOP

MAIN:	   LXI H,7500
	   MVI C,0A	// INNER LOOP
// sMALL NO INTO ACC, SMALLER INTO //MEMORY,
// MEM+, SHIFT LARGER NO

OLOOP:	   MOV A,M
	   INX H
	   MOV B,M
	   CMP B
	   JM ILOOP
	   MOV M,A
	   DCX H
	   MOV M,B
	   INX H
// DEC OF OUTER AND INNER LOOP

ILOOP:	   DCR C
	   JNZ OLOOP
	   DCR D
	   JNZ MAIN
	   HLT
# ORG 7500
# DB 10H,11H,07H,08H,04H,05H,06H,03H,02H,01H
